name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq and curl
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Get the time
        id: time
        run: |
          NOW=$(date +"%r")
          echo "now=${NOW}" >> $GITHUB_ENV
        env:
          TZ: Asia/Kolkata  # Correct timezone for India

      - name: Get IP Address and Location Information
        id: ip-info
        run: |
          # Fetch IP address
          IP=$(curl -s https://api.ipify.org)

          # Fetch location information
          RESPONSE=$(curl -s https://geolocation-db.com/json/${IP}&position=true)
          LOCATION=$(echo $RESPONSE | jq -r '.city, .state, .country_name' | paste -sd ', ')
          LAT=$(echo $RESPONSE | jq -r '.latitude')
          LONG=$(echo $RESPONSE | jq -r '.longitude')

          # Get OS and version
          OS=$(uname -s)
          OS_VERSION=$(lsb_release -ds)
          if [ "$OS" == "Linux" ]; then
            OS_VERSION_DESC=$(lsb_release -ds)
          else
            OS_VERSION_DESC="Unknown"
          fi

          # Browser is not applicable in the context of a GitHub Actions runner
          BROWSER="GitHub Actions Runner"

          # Export variables
          echo "ip=${IP}" >> $GITHUB_ENV
          echo "location=${LOCATION}" >> $GITHUB_ENV
          echo "latitude=${LAT}" >> $GITHUB_ENV
          echo "longitude=${LONG}" >> $GITHUB_ENV
          echo "os=${OS}" >> $GITHUB_ENV
          echo "os_version=${OS_VERSION_DESC}" >> $GITHUB_ENV
          echo "browser=${BROWSER}" >> $GITHUB_ENV

      - name: Send the time and IP info
        uses: satak/webrequest-action@master  # Ensure using the correct version
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          payload: |
            {
              "content": "The workflow ran at ${{ env.now }}\nIP Address: ${{ env.ip }}\nLocation: ${{ env.location }}\nLatitude: ${{ env.latitude }}\nLongitude: ${{ env.longitude }}\nOperating System: ${{ env.os }}\nOS Version: ${{ env.os_version }}\nBrowser: ${{ env.browser }}"
            }
