name: CI
on:
workflow_dispatch:
jobs:
build:
runs-on: ubuntu-latest
steps:
uses: actions/checkout@v3
name: Get the time
id: time

run: 1

NOW $(date+"r")

echo "now=$(NOW)" >> SGITHUB_OUTPUT

env:

TZ: India/TamilNadu

name: Send the time

uses: satak/webrequest-actiongmaster

with:

url: ${{ secrets.DISCORD_WEBHOOK }}

method: POST

payload: "("content": "The workflow ran at ${{ steps.tinme.outputs.now}}}
