name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the time
        id: time
        run: |
          NOW=$(date +"%r")
          echo "now=${NOW}" >> $GITHUB_ENV
        env:
          TZ: Asia/Kolkata  # Correct timezone for India

      - name: Send the time
        uses: satak/webrequest-action@master  # Ensure using the correct version
        with:
          url: https://discord.com/api/webhooks/1262504162751680582/6BqMbWkomK8CpKQl2HaHVDWS-cAFEJtmGDbjsiBvBSNk14boIbZbXGm-Px7sDzUdU0I2
          method: POST
          payload: '{"content": "The workflow ran at ${{ env.now }}"}'
